FORMAT: 1A
HOST: http://staging.muzar.cz

# muzar.cz

## Ad [/ad{?until}]

### List all text advertisment items [GET]

+ Parameters
    + until (optional, datetime) ... 
+ Response 200 (application/json)

        {
            "meta": 
            {
                "params": {},
                "nextLink": null,
                "prevLink": "http://staging.muzar.cz/ads?until=2013-10-12%2012:40:20"
            },
            "data": 
            [
                {
                  "id": 1, 
                  "name": "Fender Telecaster Mexico",
                  "imageUrl": "http://lorempixel.com/300/200",
                  "district": "Olomoucký kraj",
                  "price": 13000,
                  "description": "",
                  "created": "2013-12-12 12:45:30"
                },
                {
                  "id": 2, 
                  "name": "Fender Precision Bass",
                  "imageUrl": "http://lorempixel.com/300/200",
                  "district": "Královehradecký kraj",
                  "price": 20000,
                  "description": "",
                  "created": "2013-12-12 12:45:30"
                },
                {
                  "id": 3, 
                  "name": "Boss Metalzone",
                  "imageUrl": "http://lorempixel.com/300/200",
                  "district": "Praha",
                  "price": 700,
                  "description": "",
                  "created": "2013-11-12 12:40:20"
                },
                {
                  "id": 4, 
                  "name": "Seymour duncan humbucker",
                  "imageUrl": "http://lorempixel.com/300/200",
                  "district": "Olomoucký kraj",
                  "price": 2000,
                  "description": "",
                  "created": "2013-10-12 12:40:20"
                }
            ]
        }

## Category [/category]

### List all categories [GET]

+ Response 200 (application/json)

        {
            "meta": {},
            "data":
            [
                {
                    "strId": "kytarove-nastroje",
                    "name": "Kytarové nastroje",
                    "newSince": 10,
                    "children":
                    [
                        {
                            "strId": "elektricke-kytary",
                            "name": "Elektrické kytary",
                            "newSince": 15
                        },
                        {
                            "strId": "kytarove-aparaty",
                            "name": "Kytarové aparáty",
                            "newSince": 1
                        },
                        {
                            "strId": "akusticke-a-klasicke-kytary",
                            "name": "Akustické a klasické kytary",
                            "newSince": 2
                        }
                    ]
                },
                {
                    "strId": "bici-nastroje",
                    "name": "Bicí nastroje",
                    "newSince": 28
                }
            ]
        }
