FORMAT: 1A
HOST: http://staging.muzar.cz

# muzar.cz

## Ads [/ads{?startId}{&limit}]

### List all text advertisment items [GET]

+ Parameters
    + startId (optional, int) ... Starting ad id
    + limit (optional, int) ... How much items load
+ Response 200 (application/json)

        {
            "meta": 
            {
                "params": {
                    "limit": 6
                },
                "nextLink": "http://muzarcz.apiary.io/ad?startId=4",
                "total": 128
            },
            "data": 
            [
                {
                  "id": 1, 
                  "name": "Fender Telecaster Mexico",
                  "image_url": "http://lorempixel.com/300/200",
                  "district": "Olomoucký kraj",
                  "price": 13000,
                  "description": "",
                  "created": "2013-12-12 12:45:30"
                },
                {
                  "id": 2, 
                  "name": "Fender Precision Bass",
                  "image_url": "http://lorempixel.com/300/200",
                  "district": "Královehradecký kraj",
                  "price": 20000,
                  "description": "",
                  "created": "2013-12-12 12:45:30"
                },
                {
                  "id": 3, 
                  "name": "Boss Metalzone",
                  "image_url": "http://lorempixel.com/300/200",
                  "district": "Praha",
                  "price": 700,
                  "description": "",
                  "created": "2013-11-12 12:40:20"
                },
                {
                  "id": 4, 
                  "name": "Seymour duncan humbucker",
                  "image_url": "http://lorempixel.com/300/200",
                  "district": "Olomoucký kraj",
                  "price": 2000,
                  "description": "",
                  "created": "2013-10-12 12:40:20"
                },
                {
                  "id": 5, 
                  "name": "Korg Triton",
                  "image_url": "http://lorempixel.com/300/200",
                  "district": "Olomoucký kraj",
                  "price": 2300,
                  "description": "",
                  "created": "2013-10-12 12:40:20"
                },
                {
                  "id": 6, 
                  "name": "KP3",
                  "image_url": "http://lorempixel.com/300/200",
                  "district": "Praha",
                  "price": 6000,
                  "description": "",
                  "created": "2013-10-12 12:40:20"
                }
            ]
        }


## Ads [/ads{id}]

### List all text advertisment items [GET]

+ Response 200 (application/json)

        {
            "meta": 
            {
            },
            "data": 
            {
                "id": 2, 
                "name": "Fender Telecaster Mexico",
                "status": "active",
                "image_url": "http://placehold.it/300x200/008&text=2", 
                "district": "Olomoucký kraj",
                "price": 13000,
                "description": "",
                "created": "2013-12-12 12:45:30",
                "categories": [
                    {
                    "id": 7,
                    "str_id": "kontrabasy",
                    "name": "Kontrabasy"
                    }
                ],
                "link": "http://muzar.localhost/app_dev.php/api/ads/2"
            }
        }


## Categories [/categories]

### List all categories [GET]

+ Response 200 (application/json)

        {
            "meta": {},
            "data":
            [
                {
                    "strId": "kytarove-nastroje",
                    "name": "Kytarové nastroje",
                    "newSince": 10,
                    "children":
                    [
                        {
                            "strId": "elektricke-kytary",
                            "name": "Elektrické kytary",
                            "newSince": 15
                        },
                        {
                            "strId": "kytarove-aparaty",
                            "name": "Kytarové aparáty",
                            "newSince": 1
                        },
                        {
                            "strId": "akusticke-a-klasicke-kytary",
                            "name": "Akustické a klasické kytary",
                            "newSince": 2
                        }
                    ]
                },
                {
                    "strId": "bici-nastroje",
                    "name": "Bicí nastroje",
                    "newSince": 28
                }
            ]
        }
