FORMAT: 1A
HOST: http://staging.muzar.cz

# muzar.cz

## Items [/items]
List of text ad items
### List all text advertisment items [GET]
+ Response 200 (application/json)

        {
            "data": 
            [
                {
                  "id": 1, 
                  "name": "Fender Telecaster Mexico",
                  "description": "",
                  "created": "2013-12-12 12:45:30"
                },
                {
                  "id": 2, 
                  "name": "Fender Precision Bass",
                  "description": "",
                  "created": "2014-12-12 12:45:30"
                }
            ]
        }

